### ISSUE TITLE
CI Failing

### ISSUE THREAD

**Issue by vmuriart** [lgiordani/smallcalc#1]
* SmallCalc version: N/A
* Python version: N/A
* Operating System: N/A

### Description

Branch `Part 2` is failing CI due to interpreter `Python 3.3` missing on Travis.

**Comment by lgiordani** [comment]
Thanks, when I'll work on #3 I will also remove Python 3.3 from the CI test

**Comment by vmuriart** [comment]
You can still test with `3.3` you just need to tell travis CI to get it when it creates the environment. 
Previously it used to have available regardless of your default python (https://github.com/lgiordani/smallcalc/blob/master/.travis.yml#L5), but seems like they removed 3.3 from the pre-installed pool.

You can change the default python interpreter for each env if you want and that way you can bring back the 3.3 interpreter (though, this might be more trouble than its worth)

**Comment by lgiordani** [comment]
Thanks for the insight, I noticed they removed 3.3 when I checked why it was failing after you created the issue. I actually think it is not that worth testing Python 3.3. 3.4+ seems to be a good snapshot of what people are running nowadays

**Comment by lgiordani** [comment]
The Travis configuration is now fixed. Thanks!
