### ISSUE TITLE
Repr of Token expect

### ISSUE THREAD

**Issue by vmuriart** [lgiordani/smallcalc#3]
* SmallCalc version: N/A
* Python version: N/A
* Operating System: N/A

### Description

The `repr`/`str` output of `Token` results on an [invalid constructor](https://github.com/lgiordani/smallcalc/blob/819ec02f38b16eba9ebb21fed348a414f0640fff/smallcalc/tok.py#L15-L20). Not sure if the intent was to be able to create a proper `repr` of the `Token` that would result on a valid object when executed.

**Comment by lgiordani** [comment]
Thank you I didn't notice this problem. I will fix it and then rebase the whole project. Thanks!

**Comment by lgiordani** [comment]
Sorry, I misunderstood the issue, I wrote that code some time ago. The returned representation is not intended to be a constructor, but just a readable representation of the Token object. This is why `position` has been converted in plain `line` and `col`. Does it make sense? Let me know. Thanks

**Comment by vmuriart** [comment]
Yup makes sense. I just wanted to make sure that was the intended code 😄

**Comment by vmuriart** [comment]
To elaborate just a bit more, I wanted to verify the usage of [`repr` vs `str`](https://stackoverflow.com/a/19597196/5208670)
